name: heritage-cv-taotie
channels:
  - defaults
dependencies:
  - python=3.11.15
  - pip=26.0.1
  - setuptools=80.10.2
  - wheel=0.46.3
  - pip:
      - ultralytics==8.4.24
      - ultralytics-thop==2.0.18
      - torch==2.8.0+cu126
      - torchvision==0.23.0+cu126
      - torchaudio==2.8.0+cu126
      - opencv-python==4.13.0.92
      - pillow==12.1.1
      - numpy==2.4.3
      - matplotlib==3.10.8
      - scipy==1.17.1
      - PyYAML==6.0.3
      - requests==2.32.5
      - labelImg==1.8.6
      - lxml==6.0.2
      - python-docx>=1.1.0
      - psutil==7.2.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - typing_extensions==4.15.0
      - networkx==3.6.1
      - sympy==1.14.0
      - fsspec==2026.2.0
      - filelock==3.25.2
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.62.1
      - kiwisolver==1.5.0
      - certifi==2026.2.25
      - charset-normalizer==3.4.6
      - idna==3.11
      - urllib3==2.6.3
      - packaging==25.0
      - polars==1.39.3
      - polars-runtime-32==1.39.3
      - six==1.17.0
      - mpmath==1.3.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.18.0
